In [29]:
import pandas as pd
import requests

In [30]:
url = "https://api.themoviedb.org/3/movie/top_rated"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YWU2YjVhMDlkNzU2NzgwZjZjMWZlN2RjZmE4MmJiMCIsIm5iZiI6MTc4MTUzNDEyNy40Niwic3ViIjoiNmEzMDBkYWY4NmFlNzJkMWNmNzNhN2U2Iiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.X-G5ALYuOoFKQJa_NUtr82TCynnQHZMdcoZR95GrK1Y"
}

response = requests.get(url, headers=headers)

response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 181.2789,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.97,
   'vote_count': 1679},
  {'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'title': 'The Shawshank Redemption',
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 90.5921,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.722,
   'vote_count': 30560},
  {'adult': False,
   'backdrop_path': '/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'title': 'The Godfather',
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 41.9058,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 8.688,
   'vote_count': 23034},
  {'adult': False,
   'backdrop_path': '/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 172.0283,
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.7,
   'vote_count': 5074},
  {'adult': False,
   'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
   'genre_ids': [10402, 18],
   'id': 936075,
   'title': 'Michael',
   'original_language': 'en',
   'original_title': 'Michael',
   'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
   'popularity': 611.2146,
   'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
   'release_date': '2026-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.627,
   'vote_count': 2355},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'title': 'The Godfather Part II',
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 26.8213,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.572,
   'vote_count': 13964},
  {'adult': False,
   'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg',
   'genre_ids': [18, 9648],
   'id': 1330021,
   'title': 'Remarkably Bright Creatures',
   'original_language': 'en',
   'original_title': 'Remarkably Bright Creatures',
   'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.',
   'popularity': 35.3846,
   'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg',
   'release_date': '2026-05-07',
   'softcore': False,
   'video': False,
   'vote_average': 8.568,
   'vote_count': 613},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'title': "Schindler's List",
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 24.922,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.569,
   'vote_count': 17514},
  {'adult': False,
   'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg',
   'genre_ids': [18],
   'id': 389,
   'title': '12 Angry Men',
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 23.9117,
   'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg',
   'release_date': '1957-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.562,
   'vote_count': 10039},
  {'adult': False,
   'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'title': 'Spirited Away',
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 32.9887,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.535,
   'vote_count': 18401},
  {'adult': False,
   'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'title': 'The Dark Knight',
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 45.5647,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.531,
   'vote_count': 35900},
  {'adult': False,
   'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'title': 'Dilwale Dulhania Le Jayenge',
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 16.2892,
   'poster_path': '/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg',
   'release_date': '1995-10-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.512,
   'vote_count': 4594},
  {'adult': False,
   'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'title': 'The Green Mile',
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 26.5015,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 19324},
  {'adult': False,
   'backdrop_path': '/eeR49PafqNGOyd4WuUjtmeHqWL.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'title': 'The Lord of the Rings: The Return of the King',
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 43.8081,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 26642},
  {'adult': False,
   'backdrop_path': '/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'title': 'Parasite',
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 37.7231,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'softcore': False,
   'video': False,
   'vote_average': 8.494,
   'vote_count': 20729},
  {'adult': False,
   'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg',
   'genre_ids': [35, 10749],
   'id': 1181678,
   'title': '¿Quieres ser mi hijo?',
   'original_language': 'en',
   'original_title': '¿Quieres ser mi hijo?',
   'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.',
   'popularity': 9.6382,
   'poster_path': '/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg',
   'release_date': '2023-09-21',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 354},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80, 35],
   'id': 680,
   'title': 'Pulp Fiction',
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 35.8981,
   'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
   'release_date': '1994-09-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.483,
   'vote_count': 30275},
  {'adult': False,
   'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'title': 'Your Name.',
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 27.1624,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'softcore': False,
   'video': False,
   'vote_average': 8.481,
   'vote_count': 12613},
  {'adult': False,
   'backdrop_path': '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'title': 'Interstellar',
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 70.5263,
   'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
   'release_date': '2014-11-05',
   'softcore': False,
   'video': False,
   'vote_average': 8.478,
   'vote_count': 40009},
  {'adult': False,
   'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
   'genre_ids': [37],
   'id': 429,
   'title': 'The Good, the Bad and the Ugly',
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 22.0191,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.468,
   'vote_count': 9684}],
 'total_pages': 547,
 'total_results': 10927}

In [17]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,181.2789,8.970,1679
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,90.5921,8.722,30560
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.9058,8.688,23034
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,172.0283,8.700,5074
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,611.2146,8.627,2355
5,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,26.8213,8.572,13964
6,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,35.3846,8.568,613
7,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,24.9220,8.569,17514
8,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,23.9117,8.562,10039
9,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,32.9887,8.535,18401
10,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,45.5647,8.531,35900
11,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,16.2892,8.512,4594
12,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,26.5015,8.500,19324
13,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,43.8081,8.500,26642
14,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,37.7231,8.494,20729
15,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,9.6382,8.500,354
16,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,35.8981,8.483,30275
17,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,27.1624,8.481,12613
18,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,70.5263,8.478,40009
19,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,22.0191,8.468,9684

In [31]:
df = pd.DataFrame()

In [32]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YWU2YjVhMDlkNzU2NzgwZjZjMWZlN2RjZmE4MmJiMCIsIm5iZiI6MTc4MTUzNDEyNy40Niwic3ViIjoiNmEzMDBkYWY4NmFlNzJkMWNmNzNhN2U2Iiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.X-G5ALYuOoFKQJa_NUtr82TCynnQHZMdcoZR95GrK1Y"
}

for page in range(1,548):
    url = f"https://api.themoviedb.org/3/movie/top_rated?page={page}"
    response = requests.get(url, headers=headers)
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)

In [36]:
import requests

for i in range(5):
    r = requests.get("https://www.google.com")
    print(i, r.status_code)

0 200
1 200
2 200
3 200
4 200

In [37]:
import requests
import time

session = requests.Session()

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YWU2YjVhMDlkNzU2NzgwZjZjMWZlN2RjZmE4MmJiMCIsIm5iZiI6MTc4MTUzNDEyNy40Niwic3ViIjoiNmEzMDBkYWY4NmFlNzJkMWNmNzNhN2U2Iiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.X-G5ALYuOoFKQJa_NUtr82TCynnQHZMdcoZR95GrK1Y"
}

for page in range(1, 11):

    url = f"https://api.themoviedb.org/3/movie/top_rated?page={page}"

    try:
        response = session.get(
            url,
            headers=headers,
            timeout=30
        )

        print(
            f"Page {page} | "
            f"Status: {response.status_code}"
        )

        time.sleep(1)

    except Exception as e:
        print(f"Page {page} Error: {e}")

Page 1 Error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Page 2 | Status: 200
Page 3 | Status: 200
Page 4 | Status: 200
Page 5 | Status: 200
Page 6 | Status: 200
Page 7 | Status: 200
Page 8 | Status: 200
Page 9 | Status: 200
Page 10 | Status: 200

In [38]:
import requests
import pandas as pd
import time

session = requests.Session()

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YWU2YjVhMDlkNzU2NzgwZjZjMWZlN2RjZmE4MmJiMCIsIm5iZiI6MTc4MTUzNDEyNy40Niwic3ViIjoiNmEzMDBkYWY4NmFlNzJkMWNmNzNhN2U2Iiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.X-G5ALYuOoFKQJa_NUtr82TCynnQHZMdcoZR95GrK1Y"
}

all_movies = []

for page in range(1, 548):

    url = f"https://api.themoviedb.org/3/movie/top_rated?page={page}"

    success = False

    for attempt in range(3):

        try:
            response = session.get(
                url,
                headers=headers,
                timeout=30
            )

            data = response.json()

            all_movies.extend(data['results'])

            print(f"Downloaded page {page}")

            success = True
            break

        except Exception as e:

            print(
                f"Page {page}, "
                f"Attempt {attempt+1} failed"
            )

            time.sleep(2)

    if not success:
        print(f"Skipping page {page}")

    time.sleep(0.2)

df = pd.DataFrame(all_movies)

print("Total Movies:", len(df))

Downloaded page 1
Downloaded page 2
Downloaded page 3
Downloaded page 4
Downloaded page 5
Downloaded page 6
Downloaded page 7
Downloaded page 8
Downloaded page 9
Downloaded page 10
Downloaded page 11
Downloaded page 12
Downloaded page 13
Downloaded page 14
Downloaded page 15
Downloaded page 16
Downloaded page 17
Downloaded page 18
Downloaded page 19
Downloaded page 20
Downloaded page 21
Downloaded page 22
Downloaded page 23
Downloaded page 24
Downloaded page 25
Downloaded page 26
Downloaded page 27
Downloaded page 28
Downloaded page 29
Downloaded page 30
Downloaded page 31
Downloaded page 32
Downloaded page 33
Downloaded page 34
Downloaded page 35
Downloaded page 36
Downloaded page 37
Downloaded page 38
Downloaded page 39
Downloaded page 40
Downloaded page 41
Downloaded page 42
Downloaded page 43
Downloaded page 44
Downloaded page 45
Downloaded page 46
Downloaded page 47
Downloaded page 48
Downloaded page 49
Downloaded page 50
Downloaded page 51
Downloaded page 52
Downloaded page 53
Downloaded page 54
Downloaded page 55
Downloaded page 56
Downloaded page 57
Downloaded page 58
Downloaded page 59
Downloaded page 60
Downloaded page 61
Downloaded page 62
Downloaded page 63
Downloaded page 64
Downloaded page 65
Downloaded page 66
Downloaded page 67
Downloaded page 68
Downloaded page 69
Downloaded page 70
Downloaded page 71
Downloaded page 72
Downloaded page 73
Downloaded page 74
Downloaded page 75
Downloaded page 76
Downloaded page 77
Downloaded page 78
Downloaded page 79
Downloaded page 80
Downloaded page 81
Downloaded page 82
Downloaded page 83
Downloaded page 84
Downloaded page 85
Downloaded page 86
Downloaded page 87
Downloaded page 88
Downloaded page 89
Downloaded page 90
Downloaded page 91
Downloaded page 92
Downloaded page 93
Downloaded page 94
Downloaded page 95
Downloaded page 96
Downloaded page 97
Downloaded page 98
Downloaded page 99
Downloaded page 100
Downloaded page 101
Downloaded page 102
Downloaded page 103
Downloaded page 104
Downloaded page 105
Downloaded page 106
Downloaded page 107
Downloaded page 108
Downloaded page 109
Downloaded page 110
Downloaded page 111
Downloaded page 112
Downloaded page 113
Downloaded page 114
Downloaded page 115
Downloaded page 116
Downloaded page 117
Downloaded page 118
Downloaded page 119
Downloaded page 120
Downloaded page 121
Downloaded page 122
Downloaded page 123
Downloaded page 124
Downloaded page 125
Downloaded page 126
Downloaded page 127
Downloaded page 128
Downloaded page 129
Downloaded page 130
Downloaded page 131
Downloaded page 132
Downloaded page 133
Downloaded page 134
Downloaded page 135
Downloaded page 136
Downloaded page 137
Downloaded page 138
Downloaded page 139
Downloaded page 140
Downloaded page 141
Downloaded page 142
Downloaded page 143
Downloaded page 144
Downloaded page 145
Downloaded page 146
Downloaded page 147
Downloaded page 148
Downloaded page 149
Downloaded page 150
Downloaded page 151
Downloaded page 152
Downloaded page 153
Downloaded page 154
Downloaded page 155
Downloaded page 156
Downloaded page 157
Downloaded page 158
Downloaded page 159
Downloaded page 160
Downloaded page 161
Downloaded page 162
Downloaded page 163
Downloaded page 164
Downloaded page 165
Downloaded page 166
Downloaded page 167
Downloaded page 168
Downloaded page 169
Downloaded page 170
Downloaded page 171
Downloaded page 172
Downloaded page 173
Downloaded page 174
Downloaded page 175
Downloaded page 176
Downloaded page 177
Downloaded page 178
Downloaded page 179
Downloaded page 180
Downloaded page 181
Downloaded page 182
Downloaded page 183
Downloaded page 184
Downloaded page 185
Downloaded page 186
Downloaded page 187
Downloaded page 188
Downloaded page 189
Downloaded page 190
Downloaded page 191
Downloaded page 192
Downloaded page 193
Downloaded page 194
Downloaded page 195
Downloaded page 196
Downloaded page 197
Downloaded page 198
Downloaded page 199
Downloaded page 200
Downloaded page 201
Downloaded page 202
Downloaded page 203
Downloaded page 204
Downloaded page 205
Downloaded page 206
Downloaded page 207
Downloaded page 208
Downloaded page 209
Downloaded page 210
Downloaded page 211
Downloaded page 212
Downloaded page 213
Downloaded page 214
Downloaded page 215
Downloaded page 216
Downloaded page 217
Downloaded page 218
Downloaded page 219
Downloaded page 220
Downloaded page 221
Downloaded page 222
Downloaded page 223
Downloaded page 224
Downloaded page 225
Downloaded page 226
Downloaded page 227
Downloaded page 228
Downloaded page 229
Downloaded page 230
Downloaded page 231
Downloaded page 232
Downloaded page 233
Downloaded page 234
Downloaded page 235
Downloaded page 236
Downloaded page 237
Downloaded page 238
Downloaded page 239
Downloaded page 240
Downloaded page 241
Downloaded page 242
Downloaded page 243
Downloaded page 244
Downloaded page 245
Downloaded page 246
Downloaded page 247
Downloaded page 248
Downloaded page 249
Downloaded page 250
Downloaded page 251
Downloaded page 252
Downloaded page 253
Downloaded page 254
Downloaded page 255
Downloaded page 256
Downloaded page 257
Downloaded page 258
Downloaded page 259
Downloaded page 260
Downloaded page 261
Downloaded page 262
Downloaded page 263
Downloaded page 264
Downloaded page 265
Downloaded page 266
Downloaded page 267
Downloaded page 268
Downloaded page 269
Downloaded page 270
Downloaded page 271
Downloaded page 272
Downloaded page 273
Downloaded page 274
Downloaded page 275
Downloaded page 276
Downloaded page 277
Downloaded page 278
Downloaded page 279
Downloaded page 280
Downloaded page 281
Downloaded page 282
Downloaded page 283
Downloaded page 284
Downloaded page 285
Downloaded page 286
Downloaded page 287
Downloaded page 288
Downloaded page 289
Downloaded page 290
Downloaded page 291
Downloaded page 292
Downloaded page 293
Downloaded page 294
Downloaded page 295
Downloaded page 296
Downloaded page 297
Downloaded page 298
Downloaded page 299
Downloaded page 300
Downloaded page 301
Downloaded page 302
Downloaded page 303
Downloaded page 304
Downloaded page 305
Downloaded page 306
Downloaded page 307
Downloaded page 308
Downloaded page 309
Downloaded page 310
Downloaded page 311
Downloaded page 312
Downloaded page 313
Downloaded page 314
Downloaded page 315
Downloaded page 316
Downloaded page 317
Downloaded page 318
Downloaded page 319
Downloaded page 320
Downloaded page 321
Downloaded page 322
Downloaded page 323
Downloaded page 324
Downloaded page 325
Downloaded page 326
Downloaded page 327
Downloaded page 328
Downloaded page 329
Downloaded page 330
Downloaded page 331
Downloaded page 332
Downloaded page 333
Downloaded page 334
Downloaded page 335
Downloaded page 336
Downloaded page 337
Downloaded page 338
Downloaded page 339
Downloaded page 340
Downloaded page 341
Downloaded page 342
Downloaded page 343
Downloaded page 344
Downloaded page 345
Downloaded page 346
Downloaded page 347
Downloaded page 348
Downloaded page 349
Downloaded page 350
Downloaded page 351
Downloaded page 352
Downloaded page 353
Downloaded page 354
Downloaded page 355
Downloaded page 356
Downloaded page 357
Downloaded page 358
Downloaded page 359
Downloaded page 360
Downloaded page 361
Downloaded page 362
Downloaded page 363
Downloaded page 364
Downloaded page 365
Downloaded page 366
Downloaded page 367
Downloaded page 368
Downloaded page 369
Downloaded page 370
Downloaded page 371
Downloaded page 372
Downloaded page 373
Downloaded page 374
Downloaded page 375
Downloaded page 376
Downloaded page 377
Downloaded page 378
Downloaded page 379
Downloaded page 380
Downloaded page 381
Downloaded page 382
Downloaded page 383
Downloaded page 384
Downloaded page 385
Downloaded page 386
Downloaded page 387
Downloaded page 388
Downloaded page 389
Downloaded page 390
Downloaded page 391
Downloaded page 392
Downloaded page 393
Downloaded page 394
Downloaded page 395
Downloaded page 396
Downloaded page 397
Downloaded page 398
Downloaded page 399
Downloaded page 400
Downloaded page 401
Downloaded page 402
Downloaded page 403
Downloaded page 404
Downloaded page 405
Downloaded page 406
Downloaded page 407
Downloaded page 408
Downloaded page 409
Downloaded page 410
Downloaded page 411
Downloaded page 412
Downloaded page 413
Downloaded page 414
Downloaded page 415
Downloaded page 416
Downloaded page 417
Downloaded page 418
Downloaded page 419
Downloaded page 420
Downloaded page 421
Downloaded page 422
Downloaded page 423
Downloaded page 424
Downloaded page 425
Downloaded page 426
Downloaded page 427
Downloaded page 428
Downloaded page 429
Downloaded page 430
Downloaded page 431
Downloaded page 432
Downloaded page 433
Downloaded page 434
Downloaded page 435
Downloaded page 436
Downloaded page 437
Downloaded page 438
Downloaded page 439
Downloaded page 440
Downloaded page 441
Downloaded page 442
Downloaded page 443
Downloaded page 444
Downloaded page 445
Downloaded page 446
Downloaded page 447
Downloaded page 448
Downloaded page 449
Downloaded page 450
Downloaded page 451
Downloaded page 452
Downloaded page 453
Downloaded page 454
Downloaded page 455
Downloaded page 456
Downloaded page 457
Downloaded page 458
Downloaded page 459
Downloaded page 460
Downloaded page 461
Downloaded page 462
Downloaded page 463
Downloaded page 464
Downloaded page 465
Downloaded page 466
Downloaded page 467
Downloaded page 468
Downloaded page 469
Downloaded page 470
Downloaded page 471
Downloaded page 472
Downloaded page 473
Downloaded page 474
Downloaded page 475
Downloaded page 476
Downloaded page 477
Downloaded page 478
Downloaded page 479
Downloaded page 480
Downloaded page 481
Downloaded page 482
Downloaded page 483
Downloaded page 484
Downloaded page 485
Downloaded page 486
Downloaded page 487
Downloaded page 488
Downloaded page 489
Downloaded page 490
Downloaded page 491
Downloaded page 492
Downloaded page 493
Downloaded page 494
Downloaded page 495
Downloaded page 496
Downloaded page 497
Downloaded page 498
Downloaded page 499
Downloaded page 500
Page 501, Attempt 1 failed
Page 501, Attempt 2 failed
Page 501, Attempt 3 failed
Skipping page 501
Page 502, Attempt 1 failed
Page 502, Attempt 2 failed
Page 502, Attempt 3 failed
Skipping page 502
Page 503, Attempt 1 failed
Page 503, Attempt 2 failed
Page 503, Attempt 3 failed
Skipping page 503
Page 504, Attempt 1 failed
Page 504, Attempt 2 failed
Page 504, Attempt 3 failed
Skipping page 504
Page 505, Attempt 1 failed
Page 505, Attempt 2 failed
Page 505, Attempt 3 failed
Skipping page 505
Page 506, Attempt 1 failed
Page 506, Attempt 2 failed
Page 506, Attempt 3 failed
Skipping page 506
Page 507, Attempt 1 failed
Page 507, Attempt 2 failed
Page 507, Attempt 3 failed
Skipping page 507
Page 508, Attempt 1 failed
Page 508, Attempt 2 failed
Page 508, Attempt 3 failed
Skipping page 508
Page 509, Attempt 1 failed
Page 509, Attempt 2 failed
Page 509, Attempt 3 failed
Skipping page 509
Page 510, Attempt 1 failed
Page 510, Attempt 2 failed
Page 510, Attempt 3 failed
Skipping page 510
Page 511, Attempt 1 failed
Page 511, Attempt 2 failed
Page 511, Attempt 3 failed
Skipping page 511
Page 512, Attempt 1 failed
Page 512, Attempt 2 failed
Page 512, Attempt 3 failed
Skipping page 512
Page 513, Attempt 1 failed
Page 513, Attempt 2 failed
Page 513, Attempt 3 failed
Skipping page 513
Page 514, Attempt 1 failed
Page 514, Attempt 2 failed
Page 514, Attempt 3 failed
Skipping page 514
Page 515, Attempt 1 failed
Page 515, Attempt 2 failed
Page 515, Attempt 3 failed
Skipping page 515
Page 516, Attempt 1 failed
Page 516, Attempt 2 failed
Page 516, Attempt 3 failed
Skipping page 516
Page 517, Attempt 1 failed
Page 517, Attempt 2 failed
Page 517, Attempt 3 failed
Skipping page 517
Page 518, Attempt 1 failed
Page 518, Attempt 2 failed
Page 518, Attempt 3 failed
Skipping page 518
Page 519, Attempt 1 failed
Page 519, Attempt 2 failed
Page 519, Attempt 3 failed
Skipping page 519
Page 520, Attempt 1 failed
Page 520, Attempt 2 failed
Page 520, Attempt 3 failed
Skipping page 520
Page 521, Attempt 1 failed
Page 521, Attempt 2 failed
Page 521, Attempt 3 failed
Skipping page 521
Page 522, Attempt 1 failed
Page 522, Attempt 2 failed
Page 522, Attempt 3 failed
Skipping page 522
Page 523, Attempt 1 failed
Page 523, Attempt 2 failed
Page 523, Attempt 3 failed
Skipping page 523
Page 524, Attempt 1 failed
Page 524, Attempt 2 failed
Page 524, Attempt 3 failed
Skipping page 524
Page 525, Attempt 1 failed
Page 525, Attempt 2 failed
Page 525, Attempt 3 failed
Skipping page 525
Page 526, Attempt 1 failed
Page 526, Attempt 2 failed
Page 526, Attempt 3 failed
Skipping page 526
Page 527, Attempt 1 failed
Page 527, Attempt 2 failed
Page 527, Attempt 3 failed
Skipping page 527
Page 528, Attempt 1 failed
Page 528, Attempt 2 failed
Page 528, Attempt 3 failed
Skipping page 528
Page 529, Attempt 1 failed
Page 529, Attempt 2 failed
Page 529, Attempt 3 failed
Skipping page 529
Page 530, Attempt 1 failed
Page 530, Attempt 2 failed
Page 530, Attempt 3 failed
Skipping page 530
Page 531, Attempt 1 failed
Page 531, Attempt 2 failed
Page 531, Attempt 3 failed
Skipping page 531
Page 532, Attempt 1 failed
Page 532, Attempt 2 failed
Page 532, Attempt 3 failed
Skipping page 532
Page 533, Attempt 1 failed
Page 533, Attempt 2 failed
Page 533, Attempt 3 failed
Skipping page 533
Page 534, Attempt 1 failed
Page 534, Attempt 2 failed
Page 534, Attempt 3 failed
Skipping page 534
Page 535, Attempt 1 failed
Page 535, Attempt 2 failed
Page 535, Attempt 3 failed
Skipping page 535
Page 536, Attempt 1 failed
Page 536, Attempt 2 failed
Page 536, Attempt 3 failed
Skipping page 536
Page 537, Attempt 1 failed
Page 537, Attempt 2 failed
Page 537, Attempt 3 failed
Skipping page 537
Page 538, Attempt 1 failed
Page 538, Attempt 2 failed
Page 538, Attempt 3 failed
Skipping page 538
Page 539, Attempt 1 failed
Page 539, Attempt 2 failed
Page 539, Attempt 3 failed
Skipping page 539
Page 540, Attempt 1 failed
Page 540, Attempt 2 failed
Page 540, Attempt 3 failed
Skipping page 540
Page 541, Attempt 1 failed
Page 541, Attempt 2 failed
Page 541, Attempt 3 failed
Skipping page 541
Page 542, Attempt 1 failed
Page 542, Attempt 2 failed
Page 542, Attempt 3 failed
Skipping page 542
Page 543, Attempt 1 failed
Page 543, Attempt 2 failed
Page 543, Attempt 3 failed
Skipping page 543
Page 544, Attempt 1 failed
Page 544, Attempt 2 failed
Page 544, Attempt 3 failed
Skipping page 544
Page 545, Attempt 1 failed
Page 545, Attempt 2 failed
Page 545, Attempt 3 failed
Skipping page 545
Page 546, Attempt 1 failed
Page 546, Attempt 2 failed
Page 546, Attempt 3 failed
Skipping page 546
Page 547, Attempt 1 failed
Page 547, Attempt 2 failed
Page 547, Attempt 3 failed
Skipping page 547
Total Movies: 10000

In [39]:
temp_df = df[
    ['id','title','overview',
     'release_date','popularity',
     'vote_average','vote_count']
]

In [40]:
temp_df.to_csv('top_rated_movies.csv', index=False)

In [41]:
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,181.2789,8.970,1679
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,90.5921,8.722,30560
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.9058,8.688,23034
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,172.0283,8.700,5074
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,611.2146,8.627,2355
...,...,...,...,...,...,...,...
9995,19556,Miss March,A young man awakens from a four-year coma to h...,2009-03-13,1.7066,5.600,383
9996,11335,Popeye,"Popeye is a super-strong, spinach-scarfing sai...",1980-12-12,3.5299,5.600,705
9997,11045,Taxi,A mouthy and feisty taxicab driver has hot tip...,2004-10-06,3.9165,5.565,1172
9998,346671,Little Evil,"Gary, who has just married Samantha, the woman...",2017-08-08,1.5389,5.564,991
9999,5851,Showtime,A spoof of buddy cop movies where two very dif...,2002-03-14,2.0320,5.564,1080