In [1]:
import pandas as pd

### Working with JSON

In [2]:
pd.read_json(r'D:\mca_aiml_lab\mca_env\Datasets\train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [5]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-15,1781481601,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-15,1781481601,0.0386
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-15,1781481601,0.6640
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-15,1781481601,0.8630
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-15,1781481601,3.8700
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-15,1781481601,2.5100
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-15,1781481601,0.1710
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-15,1781481601,0.1840
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-15,1781481601,0.2810
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-15,1781481601,0.2810

### Working with SQL

In [7]:
! pip install mysql.connector

Requirement already satisfied: mysql.connector in D:\mca_aiml_lab\mca_env\Lib\site-packages (2.2.9)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import mysql.connector

In [9]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [14]:
df = pd.read_sql_query("SELECT * from city where Population > 1000000",conn)

C:\Users\HP\AppData\Local\Temp\ipykernel_16632\3170522840.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * from city where Population > 1000000",conn)

In [15]:
df

       ID          Name CountryCode          District  Population
0       1         Kabul         AFG             Kabol     1780000
1      35         Alger         DZA             Alger     2168000
2      56        Luanda         AGO            Luanda     2022000
3      69  Buenos Aires         ARG  Distrito Federal     2982146
4      70    La Matanza         ARG      Buenos Aires     1266461
..    ...           ...         ...               ...         ...
232  3798       Phoenix         USA           Arizona     1321045
233  3799     San Diego         USA        California     1223400
234  3800        Dallas         USA             Texas     1188580
235  3801   San Antonio         USA             Texas     1144646
236  4068        Harare         ZWE            Harare     1410000

[237 rows x 5 columns]